INSERT INTO MOVIE(ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,HERO_NAME,HEROIN_NAME)VALUES(1,'JAANU','WEBSERIES','1HR','SHANU','PAVI');
INSERT INTO MOVIE(ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,HERO_NAME,HEROIN_NAME)VALUES(2,'PUSHPA','MOVIE','3HR','ALLU ARJUN','RESHMIKA');
INSERT INTO MOVIE(ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,HERO_NAME,HEROIN_NAME)VALUES(3,'DEVARA','MOVIE','2HR','NTR','SRI DEVI');
INSERT INTO MOVIE(ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,HERO_NAME,HEROIN_NAME)VALUES(4,'TOLIPREMA','WEBSERIES','30MIN','KARTHICK','KUSHI');
INSERT INTO MOVIE(ID,MOVIE_NAME,MOVIE_TYPE,MOVIE_DURATION,HERO_NAME,HEROIN_NAME)VALUES(5,'AMARAN','MOVIE','2HR','DINESH','DORA');